name: HyperMobs
version: 1.2
main: com.hypertron.HyperMobs
api-version: 1.20
commands:
  hypermobs:
    aliases: [hm]
    description: Manages custom mobs.
    usage: /hypermobs <list|remove|edit|despawnall|freeze|spawn>
